# Generated by Django 3.2.12 on 2023-02-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20230203_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='categories',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
