# Generated by Django 3.2.12 on 2023-02-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_listings_bid_categories_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
