# Generated by Django 3.2.12 on 2023-02-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20230201_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auction_listings',
            options={'verbose_name_plural': 'Auction_listings'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.RenameField(
            model_name='auction_listings',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='description',
            field=models.TextField(),
        ),
    ]
