# Generated by Django 3.2.12 on 2023-02-01 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_rename_username_auction_listings_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='bids',
            field=models.ManyToManyField(blank=True, null=True, related_name='auction_listings', to='auctions.Bid'),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='category', to='auctions.Categories'),
        ),
        migrations.AlterField(
            model_name='auction_listings',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_list', to='auctions.comments'),
        ),
    ]
